Support fractions for MIC values
senaite/senaite.ast pull request #31
Opened 2023-10-18 09:44 UTC by xispa

## Description of the issue/feature this PR addresses

> [!WARNING]  
> **Review and merge https://github.com/senaite/senaite.ast/pull/29 first**

This Pull Request makes possible to capture fractions for MIC Value in sensitivity results entry, with DL operators included

## Current behavior before PR

Only numbers above 0 or with `<`, `<=`, `>`, `>=` operators at the beginning are supported

## Desired behavior after PR is merged

Only numbers and fractions above 0 or with `<`, `<=`, `>`, `>=` operators at the beginning are supported

![Captura de 2023-10-18 11-42-57](https://github.com/senaite/senaite.ast/assets/832627/158ffdf3-448a-4c90-9513-c7b830262176)

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

2023-10-20 09:33 UTC, ramonski requested changes

2023-10-20 10:13 UTC, xispa commented on src/senaite/ast/adapters/guards.py
> +
Thanks! This should make the things easier: https://github.com/senaite/senaite.ast/pull/31/commits/d3381e29b3093ca60affe53d5c42c7c1adbd9473

2023-10-20 19:07 UTC, ramonski requested changes

2023-10-21 19:31 UTC, ramonski reviewed
Thanks for the implementing the changes!

2023-10-21 19:32 UTC, merged